# DACD-HRTF open evaluation configuration

config_train = {
    "fft_length": 256,
    "sampling_rate": 44100,
    "max_frequency": 22050,
    "evaluation_frequency_range": (20, 20000),
    "sparse_sampling": "sonicom_lap",
    "lap_sparse_levels": [3, 5, 19, 100],
    "model": "AE",
    "channel_En_z": 128,
    "dim_z": 64,
    "channel_De_z": 128,
    "channel_hyper": 64,
    "hlayers_hyper": 1,
    "droprate": 0,
    "dim_user": 64,
    "dim_db": 64,
    "aux_size": 2,
    "margin": 0.3,
    "batch_size": 11,
    "epochs": 1000,
    "save_frequency": 10,
    "learning_rate": 0.001,
    "loss_weights": {
        "lsd": 1,
        "ild": 1,
        "triplet": 1,
        "cdintra_z_person": 1,
        "cdintra_z_db": 1,
    },
    "num_gpus": 1,
    "num_pts": 100,
    "use_itd_gt": True,
    "fs_upsampling": 8 * 44100,
}

config_test = {
    "fft_length": 256,
    "sampling_rate": 44100,
    "max_frequency": 22050,
    "evaluation_frequency_range": (20, 20000),
    "sparse_sampling": "sonicom_lap",
    "lap_sparse_levels": [3, 5, 19, 100],
    "model": "AE",
    "channel_En_z": 128,
    "dim_z": 64,
    "channel_De_z": 128,
    "aux_size": 2,
    "channel_hyper": 64,
    "hlayers_hyper": 1,
    "droprate": 0.0,
    "dim_user": 64,
    "dim_db": 64,
    "num_gpus": 1,
    "num_pts": 100,
    "use_itd_gt": True,
    "fs_upsampling": 8 * 44100,
}
